services:
  - type: web
    name: virtual-study-room-2
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: PORT
        value: 10000